INSERT INTO USER_INFO(USER_ID,USER_PASSWORD,USER_NAME) VALUES ('12345678','pasword1','中村');
INSERT INTO USER_INFO(USER_ID,USER_PASSWORD,USER_NAME) VALUES ('00000000','pasword2','aaaaaa');
INSERT INTO USER_INFO(USER_ID,USER_PASSWORD,USER_NAME) VALUES ('11111111','pasword3','iiiiii');